[env]
NODE_ENV=development
LOGGER_LEVEL=debug

[test]
preload = ["./scripts/testSetup"]

coverage = true
coverageSkipTestFiles = true
coverageReporter = ["text"]
coverageDir = "/dev/null"
coveragePathIgnorePatterns = [
  "dist",
  "node_modules",
  "**/*.ignore*",
]
